# spring
spring:
  datasource:
    url : jdbc:mysql://localhost:3306/analyst
    username : root
    password : pwd
    driverClassName : com.mysql.jdbc.Driver

# logback
logging:
  path: /Users/caisupeng/Downloads
  config: classpath:logback-spring.xml
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%thread] [%-5p]:[%c] -- %m%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}] -- [%-5p]: [%c] -- %m%n"