package me.bl0ckchain.sdk.mybatis.entity;

import me.bl0ckchain.sdk.mybatis.id.IdGenerator;
import me.bl0ckchain.sdk.snowflake.UUID;


/**
 * Base entity with hex id, generated by snowflake.
 * <p/>
 *
 * @author <a href="mailto:supengcai@gmail.com">supeng cai</a>
 * @version V1.0, 16/2/2
 */
public class HexEntity extends BaseEntity<String> implements IdGenerator<String> {

    /**
     * Generate hex key.
     *
     * @return
     */
    @Override
    public String generateID() {
        return UUID.nextHex();
    }
}
