package me.bl0ckchain.sdk.mybatis.entity;


import me.bl0ckchain.sdk.mybatis.id.IdGenerator;
import me.bl0ckchain.sdk.snowflake.UUID;

/**
 * Base entity with long id, generated by snowflake.
 * <p/>
 *
 * @author <a href="mailto:supengcai@gmail.com">supeng cai</a>
 * @version V1.0, 16/2/2
 */
public class LongEntity extends BaseEntity<Long> implements IdGenerator<Long> {

    /**
     * Generate long key.
     *
     * @return
     */
    @Override
    public Long generateID() {
        return UUID.next();
    }

    /**
     * Assign id when insert entity .
     */
    @Override
    public void init() {
        this.id = generateID();
    }
}
